In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"M:\ResourceManagement\after_outliers.csv")
pd.set_option('display.max_columns', None)
df.head(5)

,Unnamed: 0,State Code,District Code,India/States,Division,Group,Class,NIC Name,Main Workers - Total - Persons_log_iqr_winsor,Main Workers - Total - Males_log_iqr_winsor,Main Workers - Total - Females_log_iqr_winsor,Main Workers - Rural - Persons_log_iqr_winsor,Main Workers - Rural - Males_log_iqr_winsor,Main Workers - Rural - Females_log_iqr_winsor,Main Workers - Urban - Persons_log_iqr_winsor,Main Workers - Urban - Males_log_iqr_winsor,Main Workers - Urban - Females_log_iqr_winsor,Marginal Workers - Total - Persons_log_iqr_winsor,Marginal Workers - Total - Males_log_iqr_winsor,Marginal Workers - Total - Females_log_iqr_winsor,Marginal Workers - Rural - Persons_log_iqr_winsor,Marginal Workers - Rural - Males_log_iqr_winsor,Marginal Workers - Rural - Females_log_iqr_winsor,Marginal Workers - Urban - Persons_log_iqr_winsor,Marginal Workers - Urban - Males_log_iqr_winsor,Marginal Workers - Urban - Females_log_iqr_winsor
0,0,0,0,STATE - RAJASTHAN,0,0,0,Total,10.185502,9.540151,8.047190,9.145802,9.067907,5.493061,9.516852,9.509048,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531
1,1,0,0,STATE - RAJASTHAN,0,0,0,"Crop and animal production, hunting and relate...",10.185502,9.540151,8.047190,9.145802,9.067907,5.493061,9.516852,9.509048,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531
2,2,0,0,STATE - RAJASTHAN,0,0,0,Growing of non-perennial crops,9.463198,9.263692,7.753624,8.638525,8.373092,5.493061,8.886409,8.735525,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531
3,3,0,0,STATE - RAJASTHAN,0,0,0,"Growing of cereals (except rice), leguminous c...",9.397815,9.201501,7.673688,8.555644,8.291045,5.493061,8.834483,8.686936,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531
4,4,0,0,STATE - RAJASTHAN,0,0,0,Growing of rice,4.382027,4.276666,2.197225,3.891820,3.761200,1.945910,3.465736,3.401197,1.098612,2.639057,1.609438,2.302585,2.484907,1.098612,2.302585,1.098612,1.098612,0.000000

In [3]:
row_count = df.shape[0]
print("Number of rows:", row_count)

Number of rows: 155151

In [4]:
print(df['NIC Name'].isnull().sum())

0

In [5]:
print(df.columns)

Index(['Unnamed: 0', 'State Code', 'District Code', 'India/States', 'Division',
       'Group', 'Class', 'NIC Name',
       'Main Workers - Total - Persons_log_iqr_winsor',
       'Main Workers - Total - Males_log_iqr_winsor',
       'Main Workers - Total - Females_log_iqr_winsor',
       'Main Workers - Rural - Persons_log_iqr_winsor',
       'Main Workers - Rural - Males_log_iqr_winsor',
       'Main Workers - Rural - Females_log_iqr_winsor',
       'Main Workers - Urban - Persons_log_iqr_winsor',
       'Main Workers - Urban - Males_log_iqr_winsor',
       'Main Workers - Urban - Females_log_iqr_winsor',
       'Marginal Workers - Total - Persons_log_iqr_winsor',
       'Marginal Workers - Total - Males_log_iqr_winsor',
       'Marginal Workers - Total - Females_log_iqr_winsor',
       'Marginal Workers - Rural - Persons_log_iqr_winsor',
       'Marginal Workers - Rural - Males_log_iqr_winsor',
       'Marginal Workers - Rural - Females_log_iqr_winsor',
       'Marginal Workers - Urban - Persons_log_iqr_winsor',
       'Marginal Workers - Urban - Males_log_iqr_winsor',
       'Marginal Workers - Urban - Females_log_iqr_winsor'],
      dtype='object')

In [7]:
df["NIC Name"].unique

<bound method Series.unique of 0                                                     Total
1         Crop and animal production, hunting and relate...
2                            Growing of non-perennial crops
3         Growing of cereals (except rice), leguminous c...
4                                           Growing of rice
                                ...
155146    Undifferentiated goods- and services-producing...
155147    Undifferentiated goods-producing activities of...
155148    Activities of extraterritorial organizations a...
155149                                                Blank
155150            Incomplete description/ Wrongly Classifed
Name: NIC Name, Length: 155151, dtype: object>

In [8]:
!python -m spacy download en_core_web_md

Collecting en-core-web-md==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl (33.5 MB)
     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
      --------------------------------------- 0.8/33.5 MB 4.8 MB/s eta 0:00:07
     - -------------------------------------- 1.6/33.5 MB 4.9 MB/s eta 0:00:07
     --- ------------------------------------ 2.6/33.5 MB 4.9 MB/s eta 0:00:07
     ---- ----------------------------------- 3.7/33.5 MB 4.8 MB/s eta 0:00:07
     ----- ---------------------------------- 4.7/33.5 MB 4.8 MB/s eta 0:00:07
     ------ --------------------------------- 5.5/33.5 MB 4.7 MB/s eta 0:00:07
     ------- -------------------------------- 6.6/33.5 MB 4.7 MB/s eta 0:00:06
     -------- ------------------------------- 7.3/33.5 MB 4.6 MB/s eta 0:00:06
     ---------- ----------------------------- 8.4/33.5 MB 4.6 MB/s eta 0:00:06
     ----------- ---------------------------- 9.4/33.5 MB 4.7 MB/s eta 0:00:06
     ------------ --------------------------- 10.5/33.5 MB 4.8 MB/s eta 0:00:05
     ------------- -------------------------- 11.5/33.5 MB 4.8 MB/s eta 0:00:05
     --------------- ------------------------ 12.8/33.5 MB 4.9 MB/s eta 0:00:05
     ---------------- ----------------------- 13.9/33.5 MB 4.9 MB/s eta 0:00:04
     ----------------- ---------------------- 14.9/33.5 MB 4.9 MB/s eta 0:00:04
     ------------------- -------------------- 16.0/33.5 MB 4.9 MB/s eta 0:00:04
     -------------------- ------------------- 17.0/33.5 MB 4.9 MB/s eta 0:00:04
     --------------------- ------------------ 18.1/33.5 MB 4.9 MB/s eta 0:00:04
     ----------------------- ---------------- 19.4/33.5 MB 5.0 MB/s eta 0:00:03
     ------------------------ --------------- 20.4/33.5 MB 5.0 MB/s eta 0:00:03
     ------------------------- -------------- 21.2/33.5 MB 4.9 MB/s eta 0:00:03
     -------------------------- ------------- 22.3/33.5 MB 4.9 MB/s eta 0:00:03
     --------------------------- ------------ 23.1/33.5 MB 4.9 MB/s eta 0:00:03
     ----------------------------- ---------- 24.4/33.5 MB 4.9 MB/s eta 0:00:02
     ------------------------------ --------- 25.2/33.5 MB 4.9 MB/s eta 0:00:02
     ------------------------------- -------- 26.2/33.5 MB 4.9 MB/s eta 0:00:02
     -------------------------------- ------- 27.5/33.5 MB 4.9 MB/s eta 0:00:02
     ---------------------------------- ----- 28.6/33.5 MB 4.9 MB/s eta 0:00:01
     ----------------------------------- ---- 29.6/33.5 MB 4.9 MB/s eta 0:00:01
     ------------------------------------ --- 30.7/33.5 MB 4.9 MB/s eta 0:00:01
     ------------------------------------- -- 31.7/33.5 MB 5.0 MB/s eta 0:00:01
     ---------------------------------------  33.0/33.5 MB 5.0 MB/s eta 0:00:01
     ---------------------------------------  33.3/33.5 MB 5.0 MB/s eta 0:00:01
     ---------------------------------------- 33.5/33.5 MB 4.8 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')

In [9]:
pip install spacy

Requirement already satisfied: spacy in m:\resourcemanagement\.venv\lib\site-packages (3.8.7)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (0.16.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (2.11.7)
Requirement already satisfied: jinja2 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (65.5.0)
Requirement already satisfied: packaging>=20.0 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in m:\resourcemanagement\.venv\lib\site-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in m:\resourcemanagement\.venv\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in m:\resourcemanagement\.venv\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in m:\resourcemanagement\.venv\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in m:\resourcemanagement\.venv\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.14.1)
Requirement already satisfied: typing-inspection>=0.4.0 in m:\resourcemanagement\.venv\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in m:\resourcemanagement\.venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in m:\resourcemanagement\.venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in m:\resourcemanagement\.venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in m:\resourcemanagement\.venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.6.15)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in m:\resourcemanagement\.venv\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in m:\resourcemanagement\.venv\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: colorama in m:\resourcemanagement\.venv\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in m:\resourcemanagement\.venv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in m:\resourcemanagement\.venv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in m:\resourcemanagement\.venv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.0.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in m:\resourcemanagement\.venv\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.21.1)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in m:\resourcemanagement\.venv\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.3.0.post1)
Requirement already satisfied: wrapt in m:\resourcemanagement\.venv\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (1.17.2)
Requirement already satisfied: marisa-trie>=1.1.0 in m:\resourcemanagement\.venv\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in m:\resourcemanagement\.venv\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in m:\resourcemanagement\.venv\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in m:\resourcemanagement\.venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in m:\resourcemanagement\.venv\lib\site-packages (from jinja2->spacy) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [11]:
pip install transformers pandas

Requirement already satisfied: transformers in m:\resourcemanagement\.venv\lib\site-packages (4.53.1)
Requirement already satisfied: pandas in m:\resourcemanagement\.venv\lib\site-packages (2.3.1)
Requirement already satisfied: filelock in m:\resourcemanagement\.venv\lib\site-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in m:\resourcemanagement\.venv\lib\site-packages (from transformers) (0.33.2)
Requirement already satisfied: numpy>=1.17 in m:\resourcemanagement\.venv\lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in m:\resourcemanagement\.venv\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in m:\resourcemanagement\.venv\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in m:\resourcemanagement\.venv\lib\site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in m:\resourcemanagement\.venv\lib\site-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<0.22,>=0.21 in m:\resourcemanagement\.venv\lib\site-packages (from transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in m:\resourcemanagement\.venv\lib\site-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in m:\resourcemanagement\.venv\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in m:\resourcemanagement\.venv\lib\site-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in m:\resourcemanagement\.venv\lib\site-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.14.1)
Requirement already satisfied: python-dateutil>=2.8.2 in m:\resourcemanagement\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in m:\resourcemanagement\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in m:\resourcemanagement\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in m:\resourcemanagement\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in m:\resourcemanagement\.venv\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in m:\resourcemanagement\.venv\lib\site-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in m:\resourcemanagement\.venv\lib\site-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in m:\resourcemanagement\.venv\lib\site-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in m:\resourcemanagement\.venv\lib\site-packages (from requests->transformers) (2025.6.15)
Note: you may need to restart the kernel to use updated packages.

In [10]:
from transformers import AutoTokenizer
# Load BERT tokenizer 
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

m:\ResourceManagement\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [11]:
# Tokenize and store tokens in a new column
df['tokens'] = df['NIC Name'].apply(lambda x: tokenizer.tokenize(x))

In [12]:
df['input_ids'] = df['NIC Name'].apply(lambda x: tokenizer(x)['input_ids'])

In [13]:
print(df[['NIC Name', 'tokens', 'input_ids']])

                                                 NIC Name  \
0                                                   Total
1       Crop and animal production, hunting and relate...
2                          Growing of non-perennial crops
3       Growing of cereals (except rice), leguminous c...
4                                         Growing of rice
...                                                   ...
155146  Undifferentiated goods- and services-producing...
155147  Undifferentiated goods-producing activities of...
155148  Activities of extraterritorial organizations a...
155149                                              Blank
155150          Incomplete description/ Wrongly Classifed

                                                   tokens  \
0                                                 [total]
1       [crop, and, animal, production, ,, hunting, an...
2                 [growing, of, non, -, perennial, crops]
3       [growing, of, cereal, ##s, (, except, rice, ),...
4                                     [growing, of, rice]
...                                                   ...
155146  [und, ##iff, ##ere, ##nti, ##ated, goods, -, a...
155147  [und, ##iff, ##ere, ##nti, ##ated, goods, -, p...
155148  [activities, of, extra, ##ter, ##rito, ##rial,...
155149                                            [blank]
155150  [incomplete, description, /, wrongly, class, #...

                                                input_ids
0                                        [101, 2561, 102]
1       [101, 10416, 1998, 4111, 2537, 1010, 5933, 199...
2         [101, 3652, 1997, 2512, 1011, 14638, 8765, 102]
3       [101, 3652, 1997, 20943, 2015, 1006, 3272, 578...
4                            [101, 3652, 1997, 5785, 102]
...                                                   ...
155146  [101, 6151, 13355, 7869, 16778, 4383, 5350, 10...
155147  [101, 6151, 13355, 7869, 16778, 4383, 5350, 10...
155148  [101, 3450, 1997, 4469, 3334, 28414, 14482, 44...
155149                                   [101, 8744, 102]
155150  [101, 12958, 6412, 1013, 29116, 2465, 29323, 2...

[155151 rows x 3 columns]

In [14]:
import string
import spacy

nlp = spacy.load("en_core_web_md")  # Make sure it's installed!

# 1. Stop words from spaCy
stop_words = nlp.Defaults.stop_words

# 2. Custom meaningless/junk tokens
junk_tokens = {
    'sp', 'rs', 'ml', 'km', 'mtr', 'no', 'qty', 'mrp', 'pc', 'gm', 'ltr',
    'cm', 'nos', 'etc', 'non', 'ir', 'in', 'un', 'ing'
}

# 3. Token cleaner function
def clean_token_list(token_list):
    return [
        t for t in token_list
        if t.lower() not in stop_words                      # Remove stopwords
        and t not in string.punctuation                     # Remove punctuation
        and not (len(t) == 1 and t.isalpha())               # Remove single-letter words
        and not t.startswith("##")                          # Remove subwords like ##ing
        and t.lower() not in junk_tokens                    # Remove meaningless short tokens
        and len(t) > 1                                       # Optional: remove single character non-alpha tokens
    ]

# 4. Apply to DataFrame
df['tokens_no_stop'] = df['tokens'].apply(clean_token_list)

In [15]:
(df[['NIC Name', 'tokens', 'tokens_no_stop']])

,NIC Name,tokens,tokens_no_stop
0,Total,[total],[total]
1,"Crop and animal production, hunting and relate...","[crop, and, animal, production, ,, hunting, an...","[crop, animal, production, hunting, related, s..."
2,Growing of non-perennial crops,"[growing, of, non, -, perennial, crops]","[growing, perennial, crops]"
3,"Growing of cereals (except rice), leguminous c...","[growing, of, cereal, ##s, (, except, rice, ),...","[growing, cereal, rice, leg, crops, oil, seeds]"
4,Growing of rice,"[growing, of, rice]","[growing, rice]"
...,...,...,...
155146,Undifferentiated goods- and services-producing...,"[und, ##iff, ##ere, ##nti, ##ated, goods, -, a...","[und, goods, services, producing, activities, ..."
155147,Undifferentiated goods-producing activities of...,"[und, ##iff, ##ere, ##nti, ##ated, goods, -, p...","[und, goods, producing, activities, private, h..."
155148,Activities of extraterritorial organizations a...,"[activities, of, extra, ##ter, ##rito, ##rial,...","[activities, extra, organizations, bodies]"
155149,Blank,[blank],[blank]
155150,Incomplete description/ Wrongly Classifed,"[incomplete, description, /, wrongly, class, #...","[incomplete, description, wrongly, class]"

In [16]:
df['tokens_no_stop'][1]

['crop', 'animal', 'production', 'hunting', 'related', 'service', 'activities']

In [17]:
from itertools import chain 
all_tokens = list(chain.from_iterable(df['tokens_no_stop']))
len(all_tokens)
df['all_tokens'] = [all_tokens] * len(df)
len(all_tokens)

603762

In [18]:
clean_tokens = [token for token in all_tokens if not token.startswith("##")]
df['clean_tokens'] = [clean_tokens] * len(df)
len(clean_tokens)

603762

In [19]:
from collections import Counter 
tokens_count = Counter(clean_tokens)
df['tokens_count'] = [tokens_count] *len(df)
tokens_count

Counter({'activities': 45504,
         'manufacture': 37421,
         'products': 15160,
         'retail': 12313,
         'sale': 11963,
         'specialized': 9493,
         'service': 9301,
         'equipment': 8893,
         'stores': 7465,
         'transport': 7194,
         'repair': 6884,
         'support': 5653,
         'goods': 5590,
         'wholesale': 5282,
         'food': 4896,
         'machinery': 4815,
         'related': 4513,
         'education': 4095,
         'construction': 4066,
         'metal': 4038,
         'household': 3785,
         'motor': 3747,
         'vehicles': 3644,
         'insurance': 3312,
         'social': 3303,
         'textiles': 3267,
         'mining': 2916,
         'growing': 2912,
         'personal': 2795,
         'production': 2754,
         'organizations': 2752,
         'wood': 2723,
         'accommodation': 2587,
         'articles': 2555,
         'markets': 2423,
         'tobacco': 2347,
         'stalls': 2335,
         'trade': 2300,
         'land': 2229,
         'beverages': 2163,
         'paper': 2136,
         'installation': 2065,
         'electrical': 2061,
         'general': 2016,
         'publishing': 1996,
         'printing': 1991,
         'water': 1984,
         'apparel': 1983,
         'waste': 1938,
         'office': 1936,
         'security': 1922,
         'financial': 1912,
         'fabricated': 1882,
         'motorcycles': 1862,
         'materials': 1861,
         'passenger': 1860,
         'services': 1859,
         'telecommunications': 1850,
         'air': 1847,
         'processing': 1841,
         'pension': 1835,
         'funding': 1835,
         'raising': 1812,
         'crop': 1800,
         'transportation': 1774,
         'leather': 1756,
         'collection': 1755,
         'quarry': 1753,
         'computer': 1727,
         'technical': 1672,
         'computers': 1669,
         'business': 1665,
         'information': 1661,
         'chemical': 1653,
         'foot': 1651,
         'membership': 1645,
         'crops': 1631,
         'recreation': 1603,
         'cleaning': 1558,
         'engineering': 1540,
         'treatment': 1537,
         'gas': 1524,
         'administration': 1521,
         'public': 1497,
         'leasing': 1485,
         'finishing': 1481,
         'preparation': 1478,
         'building': 1474,
         'basic': 1467,
         'animal': 1466,
         'video': 1450,
         'work': 1396,
         'mineral': 1376,
         'furniture': 1376,
         'consultancy': 1340,
         'health': 1319,
         'television': 1315,
         'cork': 1313,
         'railways': 1296,
         'forestry': 1270,
         'motion': 1270,
         'picture': 1270,
         'textile': 1253,
         'sports': 1245,
         'compulsory': 1241,
         'arts': 1239,
         'metals': 1225,
         'beverage': 1214,
         'rubber': 1207,
         'buildings': 1207,
         'fishing': 1200,
         'fe': 1186,
         'human': 1180,
         'secondary': 1177,
         'care': 1160,
         'cultural': 1152,
         'fur': 1135,
         'freight': 1117,
         'hand': 1108,
         'perennial': 1091,
         'hardware': 1083,
         'metallic': 1082,
         'plumbing': 1082,
         'programming': 1074,
         'parts': 1073,
         'administrative': 1072,
         'amusement': 1066,
         'star': 1064,
         'preserving': 1061,
         'programme': 1060,
         'petroleum': 1019,
         'electronic': 1003,
         'electric': 999,
         'rent': 988,
         'bodies': 984,
         'clothing': 982,
         'steam': 980,
         'plastics': 978,
         'maintenance': 967,
         'supply': 959,
         'appliances': 949,
         'medical': 945,
         'management': 944,
         'music': 938,
         'agency': 930,
         'conditioning': 923,
         'aqua': 922,
         'professional': 919,
         'defence': 915,
         'trailers': 904,
         'spinning': 899,
         'post': 895,
         'wearing': 894,
         'peripheral': 894,
         'roads': 888,
         'chemicals': 886,
         'glass': 884,
         'postal': 874,
         'purpose': 871,
         'monetary': 864,
         'inter': 864,
         'manufacturing': 859,
         'employers': 853,
         'distribution': 843,
         'civil': 843,
         'research': 843,
         'weaving': 840,
         'communication': 835,
         'grain': 832,
         'mill': 832,
         'legal': 809,
         'scientific': 797,
         'ware': 792,
         'auxiliary': 791,
         'projects': 787,
         'logging': 784,
         'clay': 782,
         'harvest': 780,
         'containers': 763,
         'botanical': 761,
         'real': 760,
         'estate': 760,
         'broadcasting': 741,
         'jewellery': 737,
         'event': 735,
         'catering': 735,
         'iron': 730,
         'hazardous': 725,
         'travel': 721,
         'plan': 718,
         'rail': 713,
         'paints': 712,
         'elderly': 694,
         'pl': 691,
         'site': 690,
         'accounting': 690,
         'private': 689,
         'stone': 687,
         'courier': 686,
         'casting': 685,
         'electricity': 685,
         'books': 682,
         'agricultural': 678,
         'animals': 675,
         'sound': 675,
         'recording': 675,
         'life': 666,
         'newspapers': 655,
         'dressing': 652,
         'domestic': 652,
         'facilities': 652,
         'disposal': 648,
         'extraction': 643,
         'ore': 643,
         'structural': 643,
         'incident': 640,
         'tour': 633,
         'operator': 633,
         'testing': 632,
         'tools': 631,
         'steel': 626,
         'fibre': 622,
         'households': 618,
         'order': 615,
         'fruits': 612,
         'sugar': 608,
         'hunting': 606,
         'vegetables': 603,
         'optical': 596,
         'provision': 596,
         'residential': 592,
         'cement': 590,
         'plaster': 590,
         'lighting': 585,
         'fee': 581,
         'contract': 581,
         'basis': 581,
         'extra': 580,
         'pharmaceuticals': 576,
         'medicinal': 576,
         'natural': 571,
         'periodicals': 571,
         'supplies': 570,
         'software': 566,
         'prepared': 565,
         'primary': 565,
         'archives': 556,
         'data': 554,
         'pharmaceutical': 550,
         'development': 549,
         'refined': 538,
         'pipeline': 536,
         'dental': 526,
         'hosting': 519,
         'landscape': 517,
         'consumer': 515,
         'electronics': 515,
         'power': 500,
         'total': 494,
         'tanks': 494,
         'reservoirs': 494,
         'accessories': 494,
         'inland': 489,
         'demolition': 488,
         'blank': 486,
         'incomplete': 483,
         'description': 483,
         'wrongly': 483,
         'class': 483,
         'wiring': 480,
         'luggage': 477,
         'saddle': 477,
         'investigation': 477,
         'state': 476,
         'economic': 476,
         'policy': 476,
         'community': 466,
         'rice': 465,
         'nitrogen': 459,
         'compounds': 459,
         'transmission': 458,
         'architectural': 458,
         'tan': 452,
         'semi': 452,
         'coal': 451,
         'road': 451,
         'reins': 450,
         'special': 445,
         'straw': 444,
         'vehicle': 444,
         'home': 442,
         'safety': 439,
         'book': 437,
         'personnel': 436,
         'hospital': 433,
         'cattle': 428,
         'buffalo': 428,
         'games': 427,
         'toys': 427,
         'fuels': 425,
         'employment': 425,
         'generation': 423,
         'dairy': 421,
         'short': 421,
         'term': 421,
         'reservation': 421,
         'new': 420,
         'agriculture': 419,
         'cosmetic': 419,
         'toilet': 419,
         'educational': 419,
         'completion': 418,
         'meals': 417,
         'dishes': 417,
         'industrial': 417,
         'sea': 417,
         'coastal': 417,
         'media': 416,
         'urban': 415,
         'suburban': 415,
         'coke': 414,
         'coating': 414,
         'higher': 414,
         'museums': 414,
         'creative': 413,
         'entertainment': 413,
         'dramatic': 413,
         'combined': 412,
         'similar': 409,
         'live': 408,
         'marine': 406,
         'coach': 404,
         'cutler': 402,
         'practice': 399,
         'fish': 398,
         'crust': 398,
         'mo': 398,
         'utility': 396,
         'carpets': 394,
         'rug': 394,
         'serving': 394,
         'disabled': 391,
         'wooden': 388,
         'religious': 385,
         'hair': 385,
         'beauty': 385,
         'propagation': 383,
         'stationary': 383,
         'reproduction': 379,
         'recorded': 379,
         'central': 379,
         'knit': 378,
         'cr': 378,
         'wired': 377,
         'sand': 376,
         'raw': 373,
         'veterinary': 373,
         'restaurants': 371,
         'mobile': 371,
         'li': 370,
         'heating': 366,
         'advertising': 365,
         'regulation': 363,
         'heat': 362,
         'experimental': 362,
         'sciences': 362,
         'sheep': 361,
         'goats': 361,
         'recovery': 361,
         'storage': 361,
         'broker': 361,
         'political': 361,
         'sawmill': 359,
         'saw': 359,
         'milling': 359,
         'communications': 359,
         'automotive': 356,
         'fuel': 356,
         'washing': 355,
         'dry': 355,
         'units': 354,
         'ships': 352,
         'generators': 351,
         'fruit': 350,
         'rental': 348,
         'photo': 344,
         'document': 344,
         'instruments': 342,
         'photographic': 342,
         'bakery': 340,
         'crude': 338,
         'analysis': 334,
         'poultry': 333,
         'soap': 333,
         'deter': 333,
         'polish': 333,
         'preparations': 333,
         'garden': 329,
         'cord': 326,
         'rope': 326,
         'twin': 326,
         'netting': 326,
         'web': 318,
         'portals': 318,
         'builders': 315,
         'carp': 315,
         'join': 315,
         'und': 314,
         'producing': 314,
         'meat': 313,
         'cocoa': 311,
         'chocolate': 311,
         'con': 311,
         'bi': 310,
         'var': 308,
         'ink': 308,
         'scrap': 306,
         'devices': 302,
         'agencies': 301,
         'measuring': 298,
         'na': 298,
         'control': 298,
         'wireless': 297,
         'libraries': 296,
         'lime': 295,
         'concrete': 295,
         'soft': 294,
         'drinks': 294,
         'waters': 294,
         'market': 294,
         'operation': 294,
         'si': 293,
         'porcelain': 293,
         'ceramic': 293,
         'agents': 292,
         'banking': 290,
         'forming': 287,
         'plant': 286,
         'ref': 285,
         'audit': 282,
         'tax': 282,
         'technology': 281,
         'main': 277,
         'journals': 272,
         'vocational': 270,
         'mental': 268,
         'tyres': 267,
         'tubes': 267,
         'rebuilding': 267,
         'cutting': 267,
         'shaping': 267,
         'cereal': 265,
         'leg': 265,
         'oil': 265,
         'seeds': 265,
         'providing': 265,
         'design': 263,
         'systems': 263,
         'fr': 262,
         'motors': 262,
         'transformers': 262,
         'ag': 260,
         'handling': 260,
         'resources': 260,
         'library': 260,
         'mal': 254,
         'parks': 254,
         'mel': 253,
         'roots': 253,
         'tube': 253,
         'vegetable': 250,
         'oils': 250,
         'fat': 250,
         've': 247,
         'sheets': 247,
         'lam': 247,
         'gathering': 246,
         'forest': 246,
         'credit': 245,
         'architecture': 239,
         'precious': 236,
         'centres': 228,
         'pulp': 227,
         'like': 225,
         'harness': 225,
         'sw': 224,
         'pigs': 224,
         'leased': 223,
         'property': 223,
         'head': 223,
         'offices': 223,
         'railway': 222,
         'locomotives': 222,
         'rolling': 222,
         'stock': 222,
         'mixed': 214,
         'farming': 214,
         'freshwater': 213,
         'corrugated': 211,
         'mail': 211,
         'projection': 210,
         'fund': 210,
         'hard': 208,
         'packaging': 204,
         'satellite': 202,
         'dye': 200,
         'audio': 199,
         'radio': 196,
         'sewer': 194,
         'cargo': 194,
         'tree': 192,
         'bush': 192,
         'nuts': 192,
         'oven': 192,
         'boats': 190,
         'fabrics': 189,
         'zoological': 185,
         'gardens': 185,
         'nature': 185,
         'reserves': 185,
         'components': 182,
         'machine': 181,
         'second': 181,
         'floating': 176,
         'structures': 176,
         'houses': 176,
         'internet': 176,
         'unions': 175,
         'cables': 168,
         'trusts': 163,
         'funds': 163,
         'di': 156,
         'rec': 156,
         'blending': 156,
         'spirits': 156,
         'et': 156,
         'alcohol': 156,
         'placement': 155,
         'foreign': 150,
         'affairs': 150,
         'ole': 149,
         'musical': 149,
         'feeds': 148,
         'solid': 148,
         'liquid': 148,
         'batteries': 147,
         'acc': 147,
         'wall': 147,
         'floor': 147,
         'covering': 147,
         'recordings': 147,
         'bureau': 146,
         'trapping': 144,
         'pest': 137,
         'gambling': 136,
         'betting': 136,
         'pumps': 135,
         'compressor': 135,
         'taps': 135,
         'valves': 135,
         'nursing': 134,
         'wires': 133,
         'clubs': 133,
         'spices': 131,
         'aromatic': 131,
         'drug': 131,
         'camel': 130,
         'holding': 130,
         'companies': 130,
         'watches': 129,
         'clocks': 129,
         'wines': 127,
         'liquor': 127,
         'sporting': 125,
         'news': 124,
         'peat': 123,
         'tropical': 122,
         'subtropical': 122,
         'imitation': 122,
         'tangible': 122,
         'historical': 118,
         'sites': 118,
         'weapons': 115,
         'ammunition': 115,
         'furnishings': 113,
         'furnace': 112,
         'bearings': 109,
         'gears': 109,
         'gear': 109,
         'driving': 109,
         'elements': 109,
         'funeral': 107,
         'pressing': 106,
         'stamp': 106,
         'roll': 106,
         'powder': 106,
         'mach': 106,
         'bicycles': 105,
         'invalid': 105,
         'carriages': 105,
         'mac': 101,
         'noodles': 101,
         'co': 101,
         'far': 101,
         'opinion': 101,
         'polling': 101,
         'horses': 99,
         'salt': 99,
         'granting': 99,
         'contribution': 98,
         'efficient': 98,
         'seed': 97,
         'humanities': 95,
         'synthetic': 94,
         'forms': 94,
         'hot': 89,
         'temporary': 85,
         'engines': 83,
         'turbines': 83,
         'aircraft': 83,
         'cycle': 83,
         'theme': 79,
         'spacecraft': 77,
         'man': 70,
         'recreational': 69,
         'commodity': 69,
         'contracts': 69,
         'cane': 68,
         'substance': 67,
         'lifting': 66,
         'breeding': 65,
         'functions': 65,
         'minerals': 63,
         'citrus': 61,
         'risk': 59,
         'damage': 59,
         'evaluation': 59,
         'burn': 56,
         'organization': 51,
         'conventions': 51,
         'shows': 51,
         'driven': 48,
         'camping': 48,
         'grounds': 48,
         'trailer': 48,
         'military': 47,
         'fighting': 47,
         'po': 44,
         'tapes': 44,
         'disks': 44,
         'magnetic': 37,
         'electro': 36,
         'optic': 35,
         'director': 35,
         'lists': 35,
         'int': 30,
         'assets': 30,
         'fluid': 29,
         'anti': 24,
         'grapes': 17,
         'pleasure': 14,
         'uranium': 4,
         'thor': 4})

In [20]:
tokens_count[","]

0

In [21]:
tokens_count_df = pd.DataFrame(tokens_count.items(),columns = ["tokens", "count"])
tokens_count_df

         tokens  count
0         total    494
1          crop   1800
2        animal   1466
3    production   2754
4       hunting    606
..          ...    ...
658     wrongly    483
659       class    483
660      grapes     17
661     uranium      4
662        thor      4

[663 rows x 2 columns]

In [22]:
tokens_count_df = tokens_count_df.sort_values(by = "count", ascending = False)
tokens_count_df

          tokens  count
7     activities  45504
96   manufacture  37421
67      products  15160
394       retail  12313
396         sale  11963
..           ...    ...
215         anti     24
660       grapes     17
338     pleasure     14
661      uranium      4
662         thor      4

[663 rows x 2 columns]

In [23]:
df.head(5)

,Unnamed: 0,State Code,District Code,India/States,Division,Group,Class,NIC Name,Main Workers - Total - Persons_log_iqr_winsor,Main Workers - Total - Males_log_iqr_winsor,Main Workers - Total - Females_log_iqr_winsor,Main Workers - Rural - Persons_log_iqr_winsor,Main Workers - Rural - Males_log_iqr_winsor,Main Workers - Rural - Females_log_iqr_winsor,Main Workers - Urban - Persons_log_iqr_winsor,Main Workers - Urban - Males_log_iqr_winsor,Main Workers - Urban - Females_log_iqr_winsor,Marginal Workers - Total - Persons_log_iqr_winsor,Marginal Workers - Total - Males_log_iqr_winsor,Marginal Workers - Total - Females_log_iqr_winsor,Marginal Workers - Rural - Persons_log_iqr_winsor,Marginal Workers - Rural - Males_log_iqr_winsor,Marginal Workers - Rural - Females_log_iqr_winsor,Marginal Workers - Urban - Persons_log_iqr_winsor,Marginal Workers - Urban - Males_log_iqr_winsor,Marginal Workers - Urban - Females_log_iqr_winsor,tokens,input_ids,tokens_no_stop,all_tokens,clean_tokens,tokens_count
0,0,0,0,STATE - RAJASTHAN,0,0,0,Total,10.185502,9.540151,8.047190,9.145802,9.067907,5.493061,9.516852,9.509048,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,[total],"[101, 2561, 102]",[total],"[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '..."
1,1,0,0,STATE - RAJASTHAN,0,0,0,"Crop and animal production, hunting and relate...",10.185502,9.540151,8.047190,9.145802,9.067907,5.493061,9.516852,9.509048,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,"[crop, and, animal, production, ,, hunting, an...","[101, 10416, 1998, 4111, 2537, 1010, 5933, 199...","[crop, animal, production, hunting, related, s...","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '..."
2,2,0,0,STATE - RAJASTHAN,0,0,0,Growing of non-perennial crops,9.463198,9.263692,7.753624,8.638525,8.373092,5.493061,8.886409,8.735525,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,"[growing, of, non, -, perennial, crops]","[101, 3652, 1997, 2512, 1011, 14638, 8765, 102]","[growing, perennial, crops]","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '..."
3,3,0,0,STATE - RAJASTHAN,0,0,0,"Growing of cereals (except rice), leguminous c...",9.397815,9.201501,7.673688,8.555644,8.291045,5.493061,8.834483,8.686936,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,"[growing, of, cereal, ##s, (, except, rice, ),...","[101, 3652, 1997, 20943, 2015, 1006, 3272, 578...","[growing, cereal, rice, leg, crops, oil, seeds]","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '..."
4,4,0,0,STATE - RAJASTHAN,0,0,0,Growing of rice,4.382027,4.276666,2.197225,3.891820,3.761200,1.945910,3.465736,3.401197,1.098612,2.639057,1.609438,2.302585,2.484907,1.098612,2.302585,1.098612,1.098612,0.000000,"[growing, of, rice]","[101, 3652, 1997, 5785, 102]","[growing, rice]","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '..."

In [24]:
import pandas as pd

manual_tokens = ['retail', 'poultry', 'agriculture', 'manufacturing', 'IT services', 'service', 'sale', 
                 'organizations', 'banking', 'animal', 
                 'production', 'pharmaceutical', 'cattle', 'biotechnology', 'textiles', 'oil and gas', 
                 'telecommunications', 'automobile', 'transport', 'food', 'mining and mierals', 'construction', 
                 'education', 'insurance', 'tourism']

def check_tokens(df):
    manual_tokens_lower = [token.lower() for token in manual_tokens]

    manual_present_flags = []
    matched_tokens_list = []

    for tokens_list in df['tokens_no_stop']:
        tokens_lower = [t.lower() for t in tokens_list]

        matched = [token for token in manual_tokens_lower if token in tokens_lower]

        manual_present_flags.append('yes' if matched else 'no')
        matched_tokens_list.append(matched if matched else [])

    df['manual_token_present'] = manual_present_flags
    df['matched_manual_tokens'] = matched_tokens_list
    return df

In [25]:
df = check_tokens(df)
df_selected = df[['NIC Name', 'tokens_no_stop', 'manual_token_present', 'matched_manual_tokens']]
(df_selected)

,NIC Name,tokens_no_stop,manual_token_present,matched_manual_tokens
0,Total,[total],no,[]
1,"Crop and animal production, hunting and relate...","[crop, animal, production, hunting, related, s...",yes,"[service, animal, production]"
2,Growing of non-perennial crops,"[growing, perennial, crops]",no,[]
3,"Growing of cereals (except rice), leguminous c...","[growing, cereal, rice, leg, crops, oil, seeds]",no,[]
4,Growing of rice,"[growing, rice]",no,[]
...,...,...,...,...
155146,Undifferentiated goods- and services-producing...,"[und, goods, services, producing, activities, ...",no,[]
155147,Undifferentiated goods-producing activities of...,"[und, goods, producing, activities, private, h...",no,[]
155148,Activities of extraterritorial organizations a...,"[activities, extra, organizations, bodies]",yes,[organizations]
155149,Blank,[blank],no,[]
155150,Incomplete description/ Wrongly Classifed,"[incomplete, description, wrongly, class]",no,[]

In [26]:
from sklearn.preprocessing import MultiLabelBinarizer
import pickle

# Fit the binarizer
mlb = MultiLabelBinarizer()
binary_matrix = mlb.fit_transform(df['matched_manual_tokens'])

# Convert to DataFrame
binarized_df = pd.DataFrame(binary_matrix, columns=mlb.classes_)

# Optionally, concatenate with the original DataFrame
df_final = pd.concat([df, binarized_df], axis=1)

In [27]:
# Save the MultiLabelBinarizer object
with open('multilabel_binarizer.pkl', 'wb') as f:
    pickle.dump(mlb, f)

In [28]:
df_final

,Unnamed: 0,State Code,District Code,India/States,Division,Group,Class,NIC Name,Main Workers - Total - Persons_log_iqr_winsor,Main Workers - Total - Males_log_iqr_winsor,Main Workers - Total - Females_log_iqr_winsor,Main Workers - Rural - Persons_log_iqr_winsor,Main Workers - Rural - Males_log_iqr_winsor,Main Workers - Rural - Females_log_iqr_winsor,Main Workers - Urban - Persons_log_iqr_winsor,Main Workers - Urban - Males_log_iqr_winsor,Main Workers - Urban - Females_log_iqr_winsor,Marginal Workers - Total - Persons_log_iqr_winsor,Marginal Workers - Total - Males_log_iqr_winsor,Marginal Workers - Total - Females_log_iqr_winsor,Marginal Workers - Rural - Persons_log_iqr_winsor,Marginal Workers - Rural - Males_log_iqr_winsor,Marginal Workers - Rural - Females_log_iqr_winsor,Marginal Workers - Urban - Persons_log_iqr_winsor,Marginal Workers - Urban - Males_log_iqr_winsor,Marginal Workers - Urban - Females_log_iqr_winsor,tokens,input_ids,tokens_no_stop,all_tokens,clean_tokens,tokens_count,manual_token_present,matched_manual_tokens,agriculture,animal,banking,cattle,construction,education,food,insurance,manufacturing,organizations,pharmaceutical,poultry,production,retail,sale,service,telecommunications,textiles,transport
0,0,0,0,STATE - RAJASTHAN,0,0,0,Total,10.185502,9.540151,8.047190,9.145802,9.067907,5.493061,9.516852,9.509048,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,[total],"[101, 2561, 102]",[total],"[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,STATE - RAJASTHAN,0,0,0,"Crop and animal production, hunting and relate...",10.185502,9.540151,8.047190,9.145802,9.067907,5.493061,9.516852,9.509048,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,"[crop, and, animal, production, ,, hunting, an...","[101, 10416, 1998, 4111, 2537, 1010, 5933, 199...","[crop, animal, production, hunting, related, s...","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",yes,"[service, animal, production]",0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0
2,2,0,0,STATE - RAJASTHAN,0,0,0,Growing of non-perennial crops,9.463198,9.263692,7.753624,8.638525,8.373092,5.493061,8.886409,8.735525,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,"[growing, of, non, -, perennial, crops]","[101, 3652, 1997, 2512, 1011, 14638, 8765, 102]","[growing, perennial, crops]","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,3,0,0,STATE - RAJASTHAN,0,0,0,"Growing of cereals (except rice), leguminous c...",9.397815,9.201501,7.673688,8.555644,8.291045,5.493061,8.834483,8.686936,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,"[growing, of, cereal, ##s, (, except, rice, ),...","[101, 3652, 1997, 20943, 2015, 1006, 3272, 578...","[growing, cereal, rice, leg, crops, oil, seeds]","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,4,0,0,STATE - RAJASTHAN,0,0,0,Growing of rice,4.382027,4.276666,2.197225,3.891820,3.761200,1.945910,3.465736,3.401197,1.098612,2.639057,1.609438,2.302585,2.484907,1.098612,2.302585,1.098612,1.098612,0.000000,"[growing, of, rice]","[101, 3652, 1997, 5785, 102]","[growing, rice]","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155146,195137,0,0,District - Malkangiri,0,0,0,Undifferentiated goods- and services-producing...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147,0.000000,0.693147,0.693147,0.000000,0.693147,0.000000,0.000000,0.000000,"[und, ##iff, ##ere, ##nti, ##ated, goods, -, a...","[101, 6151, 13355, 7869, 16778, 4383, 5350, 10...","[und, goods, services, producing, activities, ...","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
155147,195138,0,0,District - Malkangiri,0,0,0,Undifferentiated goods-producing activities of...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147,0.000000,0.693147,0.693147,0.000000,0.693147,0.000000,0.000000,0.000000,"[und, ##iff, ##ere, ##nti, ##ated, goods, -, p...","[101, 6151, 13355, 7869, 16778, 4383, 5350, 10...","[und, goods, producing, activities, private, h...","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
155148,195140,0,0,District - Malkangiri,0,0,0,Activities of extraterritorial organizations a...,6.354370,5.755742,5.560682,6.212606,5.627621,5.402677,4.343805,3.663562,3.663562,7.109062,5.686975,4.864775,6.770126,5.493061,3.465736,3.850148,2.197225,2.746531,"[activities, of, extra, ##ter, ##rito, ##rial,...","[101, 3450, 1997, 4469, 3334, 28414, 14482, 44...","[activities, extra, organizations, bodies]","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",yes,[organizations],0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
155149,195141,0,0,District - Malkangiri,0,0,0,Blank,6.077642,5.587249,5.135798,5.940171,5.451038,4.997212,4.043051,3.555348,3.135494,6.375025,5.313206,4.864775,6.326149,5.293305,3.465736,3.367296,1.609438,2.746531,[blank],"[101, 8744, 102]",[blank],"[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
155150,195143,0,0,District - Malkangiri,0,0,0,Incomplete description/ Wrongly Classifed,4.941642,3.912023,4.510860,4.787492,3.828641,4.317488,3.044522,1.609438,2.833213,6.456770,4.532599,4.864775,6.428105,4.488636,3.465736,2.944439,1.609438,2.708050,"[incomplete, description, /, wrongly, class, #...","[101, 12958, 6412, 1013, 29116, 2465, 29323, 2...","[incomplete, description, wrongly, class]","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [29]:
df_final['India/States']

0             STATE - RAJASTHAN
1             STATE - RAJASTHAN
2             STATE - RAJASTHAN
3             STATE - RAJASTHAN
4             STATE - RAJASTHAN
                  ...
155146    District - Malkangiri
155147    District - Malkangiri
155148    District - Malkangiri
155149    District - Malkangiri
155150    District - Malkangiri
Name: India/States, Length: 155151, dtype: object

In [30]:
import pandas as pd
import numpy as np

# Initialize empty columns
df_final['state'] = np.where(df_final['India/States'].str.startswith('STATE'), 
                             df_final['India/States'].str.replace('STATE - ', '', regex=False), 
                             np.nan)

df_final['district'] = np.where(df_final['India/States'].str.startswith('District'), 
                                df_final['India/States'].str.replace('District - ', '', regex=False), 
                                np.nan)

In [31]:
df_final[['state', 'district']] = df_final[['state', 'district']].fillna(0)

In [32]:
df_final

,Unnamed: 0,State Code,District Code,India/States,Division,Group,Class,NIC Name,Main Workers - Total - Persons_log_iqr_winsor,Main Workers - Total - Males_log_iqr_winsor,Main Workers - Total - Females_log_iqr_winsor,Main Workers - Rural - Persons_log_iqr_winsor,Main Workers - Rural - Males_log_iqr_winsor,Main Workers - Rural - Females_log_iqr_winsor,Main Workers - Urban - Persons_log_iqr_winsor,Main Workers - Urban - Males_log_iqr_winsor,Main Workers - Urban - Females_log_iqr_winsor,Marginal Workers - Total - Persons_log_iqr_winsor,Marginal Workers - Total - Males_log_iqr_winsor,Marginal Workers - Total - Females_log_iqr_winsor,Marginal Workers - Rural - Persons_log_iqr_winsor,Marginal Workers - Rural - Males_log_iqr_winsor,Marginal Workers - Rural - Females_log_iqr_winsor,Marginal Workers - Urban - Persons_log_iqr_winsor,Marginal Workers - Urban - Males_log_iqr_winsor,Marginal Workers - Urban - Females_log_iqr_winsor,tokens,input_ids,tokens_no_stop,all_tokens,clean_tokens,tokens_count,manual_token_present,matched_manual_tokens,agriculture,animal,banking,cattle,construction,education,food,insurance,manufacturing,organizations,pharmaceutical,poultry,production,retail,sale,service,telecommunications,textiles,transport,state,district
0,0,0,0,STATE - RAJASTHAN,0,0,0,Total,10.185502,9.540151,8.047190,9.145802,9.067907,5.493061,9.516852,9.509048,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,[total],"[101, 2561, 102]",[total],"[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RAJASTHAN,0
1,1,0,0,STATE - RAJASTHAN,0,0,0,"Crop and animal production, hunting and relate...",10.185502,9.540151,8.047190,9.145802,9.067907,5.493061,9.516852,9.509048,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,"[crop, and, animal, production, ,, hunting, an...","[101, 10416, 1998, 4111, 2537, 1010, 5933, 199...","[crop, animal, production, hunting, related, s...","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",yes,"[service, animal, production]",0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,RAJASTHAN,0
2,2,0,0,STATE - RAJASTHAN,0,0,0,Growing of non-perennial crops,9.463198,9.263692,7.753624,8.638525,8.373092,5.493061,8.886409,8.735525,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,"[growing, of, non, -, perennial, crops]","[101, 3652, 1997, 2512, 1011, 14638, 8765, 102]","[growing, perennial, crops]","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RAJASTHAN,0
3,3,0,0,STATE - RAJASTHAN,0,0,0,"Growing of cereals (except rice), leguminous c...",9.397815,9.201501,7.673688,8.555644,8.291045,5.493061,8.834483,8.686936,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,"[growing, of, cereal, ##s, (, except, rice, ),...","[101, 3652, 1997, 20943, 2015, 1006, 3272, 578...","[growing, cereal, rice, leg, crops, oil, seeds]","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RAJASTHAN,0
4,4,0,0,STATE - RAJASTHAN,0,0,0,Growing of rice,4.382027,4.276666,2.197225,3.891820,3.761200,1.945910,3.465736,3.401197,1.098612,2.639057,1.609438,2.302585,2.484907,1.098612,2.302585,1.098612,1.098612,0.000000,"[growing, of, rice]","[101, 3652, 1997, 5785, 102]","[growing, rice]","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RAJASTHAN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155146,195137,0,0,District - Malkangiri,0,0,0,Undifferentiated goods- and services-producing...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147,0.000000,0.693147,0.693147,0.000000,0.693147,0.000000,0.000000,0.000000,"[und, ##iff, ##ere, ##nti, ##ated, goods, -, a...","[101, 6151, 13355, 7869, 16778, 4383, 5350, 10...","[und, goods, services, producing, activities, ...","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Malkangiri
155147,195138,0,0,District - Malkangiri,0,0,0,Undifferentiated goods-producing activities of...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147,0.000000,0.693147,0.693147,0.000000,0.693147,0.000000,0.000000,0.000000,"[und, ##iff, ##ere, ##nti, ##ated, goods, -, p...","[101, 6151, 13355, 7869, 16778, 4383, 5350, 10...","[und, goods, producing, activities, private, h...","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Malkangiri
155148,195140,0,0,District - Malkangiri,0,0,0,Activities of extraterritorial organizations a...,6.354370,5.755742,5.560682,6.212606,5.627621,5.402677,4.343805,3.663562,3.663562,7.109062,5.686975,4.864775,6.770126,5.493061,3.465736,3.850148,2.197225,2.746531,"[activities, of, extra, ##ter, ##rito, ##rial,...","[101, 3450, 1997, 4469, 3334, 28414, 14482, 44...","[activities, extra, organizations, bodies]","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",yes,[organizations],0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,Malkangiri
155149,195141,0,0,District - Malkangiri,0,0,0,Blank,6.077642,5.587249,5.135798,5.940171,5.451038,4.997212,4.043051,3.555348,3.135494,6.375025,5.313206,4.864775,6.326149,5.293305,3.465736,3.367296,1.609438,2.746531,[blank],"[101, 8744, 102]",[blank],"[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Malkangiri
155150,195143,0,0,District - Malkangiri,0,0,0,Incomplete description/ Wrongly Classifed,4.941642,3.912023,4.510860,4.787492,3.828641,4.317488,3.044522,1.609438,2.833213,6.456770,4.532599,4.864775,6.428105,4.488636,3.465736,2.944439,1.609438,2.708050,"[incomplete, description, /, wrongly, class, #...","[101, 12958, 6412, 1013, 29116, 2465, 29323, 2...","[incomplete, description, wrongly, class]","[total, crop, animal, production, hunting, rel...","[total, crop, animal, production, hunting, rel...","{'total': 494, 'crop': 1800, 'animal': 1466, '...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Malkangiri

In [33]:
df_final.isnull().sum()

Unnamed: 0                                           0
State Code                                           0
District Code                                        0
India/States                                         0
Division                                             0
Group                                                0
Class                                                0
NIC Name                                             0
Main Workers - Total - Persons_log_iqr_winsor        0
Main Workers - Total - Males_log_iqr_winsor          0
Main Workers - Total - Females_log_iqr_winsor        0
Main Workers - Rural - Persons_log_iqr_winsor        0
Main Workers - Rural - Males_log_iqr_winsor          0
Main Workers - Rural - Females_log_iqr_winsor        0
Main Workers - Urban - Persons_log_iqr_winsor        0
Main Workers - Urban - Males_log_iqr_winsor          0
Main Workers - Urban - Females_log_iqr_winsor        0
Marginal Workers - Total - Persons_log_iqr_winsor    0
Marginal Workers - Total - Males_log_iqr_winsor      0
Marginal Workers - Total - Females_log_iqr_winsor    0
Marginal Workers - Rural - Persons_log_iqr_winsor    0
Marginal Workers - Rural - Males_log_iqr_winsor      0
Marginal Workers - Rural - Females_log_iqr_winsor    0
Marginal Workers - Urban - Persons_log_iqr_winsor    0
Marginal Workers - Urban - Males_log_iqr_winsor      0
Marginal Workers - Urban - Females_log_iqr_winsor    0
tokens                                               0
input_ids                                            0
tokens_no_stop                                       0
all_tokens                                           0
clean_tokens                                         0
tokens_count                                         0
manual_token_present                                 0
matched_manual_tokens                                0
agriculture                                          0
animal                                               0
banking                                              0
cattle                                               0
construction                                         0
education                                            0
food                                                 0
insurance                                            0
manufacturing                                        0
organizations                                        0
pharmaceutical                                       0
poultry                                              0
production                                           0
retail                                               0
sale                                                 0
service                                              0
telecommunications                                   0
textiles                                             0
transport                                            0
state                                                0
district                                             0
dtype: int64

In [34]:
df_final.dtypes

Unnamed: 0                                             int64
State Code                                             int64
District Code                                          int64
India/States                                          object
Division                                               int64
Group                                                  int64
Class                                                  int64
NIC Name                                              object
Main Workers - Total - Persons_log_iqr_winsor        float64
Main Workers - Total - Males_log_iqr_winsor          float64
Main Workers - Total - Females_log_iqr_winsor        float64
Main Workers - Rural - Persons_log_iqr_winsor        float64
Main Workers - Rural - Males_log_iqr_winsor          float64
Main Workers - Rural - Females_log_iqr_winsor        float64
Main Workers - Urban - Persons_log_iqr_winsor        float64
Main Workers - Urban - Males_log_iqr_winsor          float64
Main Workers - Urban - Females_log_iqr_winsor        float64
Marginal Workers - Total - Persons_log_iqr_winsor    float64
Marginal Workers - Total - Males_log_iqr_winsor      float64
Marginal Workers - Total - Females_log_iqr_winsor    float64
Marginal Workers - Rural - Persons_log_iqr_winsor    float64
Marginal Workers - Rural - Males_log_iqr_winsor      float64
Marginal Workers - Rural - Females_log_iqr_winsor    float64
Marginal Workers - Urban - Persons_log_iqr_winsor    float64
Marginal Workers - Urban - Males_log_iqr_winsor      float64
Marginal Workers - Urban - Females_log_iqr_winsor    float64
tokens                                                object
input_ids                                             object
tokens_no_stop                                        object
all_tokens                                            object
clean_tokens                                          object
tokens_count                                          object
manual_token_present                                  object
matched_manual_tokens                                 object
agriculture                                            int64
animal                                                 int64
banking                                                int64
cattle                                                 int64
construction                                           int64
education                                              int64
food                                                   int64
insurance                                              int64
manufacturing                                          int64
organizations                                          int64
pharmaceutical                                         int64
poultry                                                int64
production                                             int64
retail                                                 int64
sale                                                   int64
service                                                int64
telecommunications                                     int64
textiles                                               int64
transport                                              int64
state                                                 object
district                                              object
dtype: object

In [35]:
df_final.drop(columns=['Unnamed: 0', 'NIC Name', 'India/States', 'tokens','input_ids', 'all_tokens',	'clean_tokens',	'tokens_count'], inplace=True)

In [36]:
df_final

,State Code,District Code,Division,Group,Class,Main Workers - Total - Persons_log_iqr_winsor,Main Workers - Total - Males_log_iqr_winsor,Main Workers - Total - Females_log_iqr_winsor,Main Workers - Rural - Persons_log_iqr_winsor,Main Workers - Rural - Males_log_iqr_winsor,Main Workers - Rural - Females_log_iqr_winsor,Main Workers - Urban - Persons_log_iqr_winsor,Main Workers - Urban - Males_log_iqr_winsor,Main Workers - Urban - Females_log_iqr_winsor,Marginal Workers - Total - Persons_log_iqr_winsor,Marginal Workers - Total - Males_log_iqr_winsor,Marginal Workers - Total - Females_log_iqr_winsor,Marginal Workers - Rural - Persons_log_iqr_winsor,Marginal Workers - Rural - Males_log_iqr_winsor,Marginal Workers - Rural - Females_log_iqr_winsor,Marginal Workers - Urban - Persons_log_iqr_winsor,Marginal Workers - Urban - Males_log_iqr_winsor,Marginal Workers - Urban - Females_log_iqr_winsor,tokens_no_stop,manual_token_present,matched_manual_tokens,agriculture,animal,banking,cattle,construction,education,food,insurance,manufacturing,organizations,pharmaceutical,poultry,production,retail,sale,service,telecommunications,textiles,transport,state,district
0,0,0,0,0,0,10.185502,9.540151,8.047190,9.145802,9.067907,5.493061,9.516852,9.509048,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,[total],no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RAJASTHAN,0
1,0,0,0,0,0,10.185502,9.540151,8.047190,9.145802,9.067907,5.493061,9.516852,9.509048,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,"[crop, animal, production, hunting, related, s...",yes,"[service, animal, production]",0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,RAJASTHAN,0
2,0,0,0,0,0,9.463198,9.263692,7.753624,8.638525,8.373092,5.493061,8.886409,8.735525,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,"[growing, perennial, crops]",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RAJASTHAN,0
3,0,0,0,0,0,9.397815,9.201501,7.673688,8.555644,8.291045,5.493061,8.834483,8.686936,6.412373,8.418240,7.361097,4.864775,6.770126,5.493061,3.465736,5.756463,4.864775,2.746531,"[growing, cereal, rice, leg, crops, oil, seeds]",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RAJASTHAN,0
4,0,0,0,0,0,4.382027,4.276666,2.197225,3.891820,3.761200,1.945910,3.465736,3.401197,1.098612,2.639057,1.609438,2.302585,2.484907,1.098612,2.302585,1.098612,1.098612,0.000000,"[growing, rice]",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RAJASTHAN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155146,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147,0.000000,0.693147,0.693147,0.000000,0.693147,0.000000,0.000000,0.000000,"[und, goods, services, producing, activities, ...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Malkangiri
155147,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147,0.000000,0.693147,0.693147,0.000000,0.693147,0.000000,0.000000,0.000000,"[und, goods, producing, activities, private, h...",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Malkangiri
155148,0,0,0,0,0,6.354370,5.755742,5.560682,6.212606,5.627621,5.402677,4.343805,3.663562,3.663562,7.109062,5.686975,4.864775,6.770126,5.493061,3.465736,3.850148,2.197225,2.746531,"[activities, extra, organizations, bodies]",yes,[organizations],0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,Malkangiri
155149,0,0,0,0,0,6.077642,5.587249,5.135798,5.940171,5.451038,4.997212,4.043051,3.555348,3.135494,6.375025,5.313206,4.864775,6.326149,5.293305,3.465736,3.367296,1.609438,2.746531,[blank],no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Malkangiri
155150,0,0,0,0,0,4.941642,3.912023,4.510860,4.787492,3.828641,4.317488,3.044522,1.609438,2.833213,6.456770,4.532599,4.864775,6.428105,4.488636,3.465736,2.944439,1.609438,2.708050,"[incomplete, description, wrongly, class]",no,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Malkangiri

In [ ]:
#Changing the name 0 to Unknown in district column
# 1. Count the values in the 'district' column
district_counts = df_final['district'].value_counts()

# 2. Convert the index to string so all values, including 0, are treated consistently
district_counts.index = district_counts.index.astype(str)

# 3. Optionally rename '0' to something meaningful like 'UNKNOWN'
district_counts.rename(index={'0': 'UNKNOWN'}, inplace=True)

# 4. Create a mapping dictionary from state_counts
state_counts_dict = district_counts.to_dict()

# 5. Ensure 'state' column is also treated as string in main DataFrame for consistent mapping
df_final['district'] = df_final['district'].astype(str)
df_final['district'] = df_final['district'].replace({'0': 'UNKNOWN'})

# 6. Map the state counts to a new column in df
df_final['district_count'] = df_final['district'].map(state_counts_dict)

# 7. Display result
print(df_final[['district', 'district_count']].head())

  district  district_count
0  UNKNOWN           11606
1  UNKNOWN           11606
2  UNKNOWN           11606
3  UNKNOWN           11606
4  UNKNOWN           11606

In [40]:
print(df_final['district'].value_counts())

district
UNKNOWN                       11606
North Twenty Four Parganas      584
Jaipur                          575
Hugli                           574
Kolkata                         574
                              ...
Mahe                             10
Kaushambi                         9
Kannauj                           7
Mainpuri                          7
Baghpat                           2
Name: count, Length: 469, dtype: int64

In [41]:
#Changing the name 0 to Unknown in state column
# 1. Count the values in the 'state' column
state_counts = df_final['state'].value_counts()

# 2. Convert the index to string so all values, including 0, are treated consistently
state_counts.index = state_counts.index.astype(str)

# 3. Optionally rename '0' to something meaningful like 'UNKNOWN'
state_counts.rename(index={'0': 'UNKNOWN'}, inplace=True)

# 4. Create a mapping dictionary from state_counts
state_counts_dict = state_counts.to_dict()

# 5. Ensure 'state' column is also treated as string in main DataFrame for consistent mapping
df_final['state'] = df_final['state'].astype(str)
df_final['state'] = df_final['state'].replace({'0': 'UNKNOWN'})

# 6. Map the state counts to a new column in df
df_final['state_count'] = df_final['state'].map(state_counts_dict)

# 7. Display result
print(df_final[['state', 'state_count']].head())

       state  state_count
0  RAJASTHAN          587
1  RAJASTHAN          587
2  RAJASTHAN          587
3  RAJASTHAN          587
4  RAJASTHAN          587

In [42]:
print(df_final['state'].value_counts())

state
UNKNOWN              143545
WEST BENGAL             588
RAJASTHAN               587
KARNATAKA               582
TAMIL NADU              577
MAHARASHTRA             576
NCT OF DELHI            563
KERALA                  556
GUJARAT                 551
ODISHA                  545
JHARKHAND               539
ASSAM                   522
MANIPUR                 516
UTTAR PRADESH           501
ARUNACHAL PRADESH       493
MIZORAM                 493
NAGALAND                486
HIMACHAL PRADESH        467
BIHAR                   458
PUDUCHERRY              432
UTTARAKHAND             425
SIKKIM                  416
TRIPURA                 408
GOA                     325
Name: count, dtype: int64

In [43]:
df_final.to_csv("after_nlp_mlb.csv")